
GET http://localhost:8000

###
GET http://localhost:8000/channels

### Get detail channels
GET http://localhost:8000/channels/2

### Create channel data
POST http://localhost:8000/channels
Content-Type: application/json

{
    "name": "Podcast dedy",
    "description": "ngomongin orang",
    "user_id":3
}

### Update channel data
PUT http://localhost:8000/channels/1
Content-Type: application/json

{
    "name": "Ganti judul"
    // "description": "Ganti description"
}

### Delete channel data
DELETE  http://localhost:8000/channels/2




// VIDEO api
GET http://localhost:8000

###
GET http://localhost:8000/videos

### Get detail videos
GET http://localhost:8000/videos/1

### Create video data
POST http://localhost:8000/videos
Content-Type: application/json

{
    "channel_id": 3,
    "title": "Reksa Dana 2",
    "description": "Cara menabung untuk senior"
}

### Update video data
PUT http://localhost:8000/videos/1
Content-Type: application/json

{
    "title": "Ganti judul"
    // "description": "Ganti description"
}

### Delete video data
DELETE  http://localhost:8000/channels/1


### Create user
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Dono",
    "email": "dono@mail.com",
    "password": "password123"
}

### List user
GET http://localhost:8000/users

### Get user
GET http://localhost:8000/videos/1

### Get video
GET http://localhost:8000/videos

### COMMENT VIDEO
POST http://localhost:8000/videos-add-comment/
Content-Type: application/json

{
    "name": "Tes komen",
    "user_id" : 1,
    "video_id" : 1
}

### UNCOMMENT VIDEO
POST http://localhost:8000/videos-add-uncomment/
Content-Type: application/json

{
    "name": "Tes komen",
    "user_id" : 1,
    "video_id" : 1
}


### Get all playlist
GET http://localhost:8000/playlists

### Get detail playlists
GET http://localhost:8000/playlists/1

### Create playlist data
POST http://localhost:8000/playlists
Content-Type: application/json

{
    "name": "lala",
    "description": "lalal poo",
    "channel_id" : 1
}

### Update playlist data
PUT http://localhost:8000/playlists/4
Content-Type: application/json

{
     "name": "lala",
    "description": "lalal poo",
    "channel_id" : 1
}

### Delete playlist data
DELETE  http://localhost:8000/playlists/2

### AddPlaylistVideo
POST http://localhost:8000/playlists/addPlaylist
Content-Type: application/json

{
    "video_id" : 1,
    "playlist_id" : 1
}

### AddPlaylistVideo
POST http://localhost:8000/playlists/delPlaylist
Content-Type: application/json

{
    "video_id" : 1,
    "playlist_id" : 1
}

### DelPlaylistVideo
DELETE  http://localhost:8000/playlists/1
Content-Type: application/json

