openapi: 3.0.1
info:
  title: YouTube API
  description: Aplikasi mirip youtube
  contact:
    email: itsme@tatanga.dev
  version: 1.0.0
servers:
  - url: http://localhost:50050
tags:
  - name: Auth
    description: Everything about auth
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Mendaftarkan user baru (summary)
      description: Mendaftarkan user baru (description)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: sabrina
                email:
                 type: string
                 example: sabrina@mail.com
                password:
                  type: string
                  example: password123
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                        example: 1
                      name:
                        type: string
                        example: sabrina
                      email:
                        type: string
                        example: sabrina@mail.com
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Name, Email and Password must be provided
                  data:
                    type: object
  /login:
    post:
      tags:
        - Auth
      summary: Masuk kedalam sistem (summary)
      description: Masuk kedalam sistem (description)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: sabrina@mail.com
                password:
                  type: string
                  example: password123
      responses:
        "201":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Email and Password is not valid
                  data:
                    type: object