openapi: 3.0.0
info:
  title: YouTube Like
  description: |-
    Aplikasi sederhana yang terinspirasi dari YouTube
  contact:
    email: itsme@tatang.dev
  version: 1.0.0
servers:
  - url: http://localhost:50050
    description: Test local computer
  - url: https://test.youtube-like.com
    description: Staging
  - url: https://youtube-like.com
    description: Production
tags:
  - name: Auth
    description: Proses Autentikasi
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Mendaftarkan User Baru
      description: Mendaftarkan User Baru (desc)
      operationId: post-register-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: sabrina
                email:
                  type: string
                  example: sabrina@mail.com
                password:
                  type: string
                  example: password123
      responses:
        "201":
          description: Success Register
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: sabrina
                      email:
                        type: string
                        example: sabrina@mail.com
        "400":
          description: Error from user
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: boolean
                        example: false
                      message:
                        type: string
                        example: email already used!
                      data: 
                        type: object
                  - type: object
                    properties:
                      status:
                        type: boolean
                        example: false
                      message:
                        type: string
                        example: name, email and password is required!
                      data: 
                        type: object
              examples:
                duplicated-email:
                  summary: If email already used
                  value:
                    status: false
                    message: email already used!
                    data: {}
                bad-request:
                  summary: If required data is not provided
                  value:
                    status: false
                    message: name, email and password is required!
                    data: {}
                    
  /login:
    post:
      tags:
        - Auth
      summary: Mendapatkan token
      description: Mendapatkan token (desc)
      operationId: post-login-user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: sabrina@mail.com
                password:
                  type: string
                  example: password123
      responses:
        "200":
          description: Success Register
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: success
                  data: 
                    type: object
                    properties:
                      token:
                        type: string
        "400":
          description: Error from user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: email or password is invalid!
                  data: 
                    type: object