POST http://localhost:3000/articles
Content-Type: application/json

{
    "title":"Mobil termurah",
    "body":"Mobil termurah, nomor 10 bikin tercengang"
}

###

GET http://localhost:3000/articles

###

GET http://localhost:3000/articles/2

