
GET http://localhost:8000

###
GET http://localhost:8000/channels

### Get detail channels
GET http://localhost:8000/channels/1

### Create channel data
POST http://localhost:8000/channels
Content-Type: application/json

{
    "name": "Podcast Coding",
    "description": "ngomongin koding"
}

### Update channel data
PUT http://localhost:8000/channels/1
Content-Type: application/json

{
    "name": "Ganti judul"
    // "description": "Ganti description"
}

### Delete channel data
DELETE  http://localhost:8000/channels/2




// VIDEO api
GET http://localhost:8000

###
GET http://localhost:8000/videos

### Get detail videos
GET http://localhost:8000/videos/1

### Create video data
POST http://localhost:8000/videos
Content-Type: application/json

{
    "channel_id": 1,
    "title": "Reksa Dana 5",
    "description": "Cara menabung untuk pemula"
}

### Update video data
PUT http://localhost:8000/videos/1
Content-Type: application/json

{
    "title": "Ganti judul"
    // "description": "Ganti description"
}

### Delete video data
DELETE  http://localhost:8000/channels/1

